In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('tmdb_movies_data.csv')

In [4]:
df

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,NaN,Bruce Brown,NaN,...,"The Endless Summer, by Bruce Brown, is one of ...",95,Documentary,Bruce Brown Films,6/15/1966,11,7.4,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,NaN,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/1966,20,5.7,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,NaN,Eldar Ryazanov,NaN,...,An insurance agent who moonlights as a carthie...,94,Mystery|Comedy,Mosfilm,1/1/1966,11,6.5,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,NaN,Woody Allen,WOODY ALLEN STRIKES BACK!,...,"In comic Woody Allen's film debut, he took the...",80,Action|Comedy,Benedict Pictures Corp.,11/2/1966,22,5.4,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,NaN,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74,Horror,Norm-Iris,11/15/1966,15,1.5,1966,1.276423e+05,0.000000e+00

In [6]:
df.shape

(10866, 21)

In [10]:
df.isnull().sum()

id                         0
imdb_id                   10
popularity                 0
budget                     0
revenue                    0
original_title             0
cast                      76
homepage                7930
director                  44
tagline                 2824
keywords                1493
overview                   4
runtime                    0
genres                    23
production_companies    1030
release_date               0
vote_count                 0
vote_average               0
release_year               0
budget_adj                 0
revenue_adj                0
dtype: int64

In [12]:
df.drop('homepage',inplace=True,axis=1)

In [15]:
df[['budget','revenue']].corr()

           budget   revenue
budget   1.000000  0.734901
revenue  0.734901  1.000000

In [16]:
df.drop(['budget_adj','revenue_adj','overview','imdb_id','tagline'],axis =1,inplace = True)

In [17]:
df

,id,popularity,budget,revenue,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,135397,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,76341,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,future|chase|post-apocalyptic|dystopia|australia,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,262500,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,based on novel|revolution|dystopia|sequel|dyst...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,140607,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,android|spaceship|jedi|space opera|3d,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,168259,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,car race|speed|revenge|suspense|car,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10861,21,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,Bruce Brown,surfer|surfboard|surfing,95,Documentary,Bruce Brown Films,6/15/1966,11,7.4,1966
10862,20379,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,John Frankenheimer,car race|racing|formula 1,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/1966,20,5.7,1966
10863,39768,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,Eldar Ryazanov,car|trolley|stealing car,94,Mystery|Comedy,Mosfilm,1/1/1966,11,6.5,1966
10864,21449,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,Woody Allen,spoof,80,Action|Comedy,Benedict Pictures Corp.,11/2/1966,22,5.4,1966
10865,22293,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,Harold P. Warren,fire|gun|drive|sacrifice|flashlight,74,Horror,Norm-Iris,11/15/1966,15,1.5,1966

In [73]:
movie = df.copy(deep=True)

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
enc = LabelEncoder()

In [78]:
movie['genres'] = enc.fit_transform(movie['genres'].values)

In [228]:
movie[['genres','popularity']].corr()

              genres  popularity
genres      1.000000   -0.072767
popularity -0.072767    1.000000

In [80]:
movie

,id,popularity,budget,revenue,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year
0,135397,32.985763,150000000.0,1.513529e+09,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,124.0,73,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015
1,76341,28.419936,150000000.0,3.784364e+08,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,future|chase|post-apocalyptic|dystopia|australia,120.0,73,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015
2,262500,13.112507,110000000.0,2.952382e+08,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,based on novel|revolution|dystopia|sequel|dyst...,119.0,338,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015
3,140607,11.173104,200000000.0,2.068178e+09,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,android|spaceship|jedi|space opera|3d,136.0,72,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015
4,168259,9.335014,190000000.0,1.506249e+09,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,car race|speed|revenge|suspense|car,137.0,130,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10822,396,0.670274,7500000.0,3.373669e+07,Who's Afraid of Virginia Woolf?,Elizabeth Taylor|Richard Burton|George Segal|S...,Mike Nichols,alcohol|adultery|professor|married couple|son,131.0,530,Chenault Productions,6/21/1966,74,7.5,1966
10828,5780,0.402730,3000000.0,1.300000e+07,Torn Curtain,Paul Newman|Julie Andrews|Lila Kedrova|HansjÃ¶...,Alfred Hitchcock,cold war|east germany,128.0,849,Universal Pictures,7/13/1966,46,6.3,1966
10829,6644,0.395668,4653000.0,6.000000e+06,El Dorado,John Wayne|Robert Mitchum|James Caan|Charlene ...,Howard Hawks,sheriff|ranch|liquor|settler|revolver,120.0,213,Paramount Pictures|Laurel Productions,12/17/1966,36,6.9,1966
10835,5923,0.299911,12000000.0,2.000000e+07,The Sand Pebbles,Steve McQueen|Richard Attenborough|Richard Cre...,Robert Wise,missionary|china|us navy|chinese|battle,182.0,51,Twentieth Century Fox Film Corporation|Solar P...,12/20/1966,28,7.0,1966
10848,2161,0.207257,5115000.0,1.200000e+07,Fantastic Voyage,Stephen Boyd|Raquel Welch|Edmond O'Brien|Donal...,Richard Fleischer,submarine|coma|claustrophobia|wound|laser,100.0,335,Twentieth Century Fox Film Corporation,8/24/1966,42,6.7,1966

In [81]:
movie['release_date'] = pd.to_datetime(movie['release_date'])
movie['release_date'].head()

0   2015-06-09
1   2015-05-13
2   2015-03-18
3   2015-12-15
4   2015-04-01
Name: release_date, dtype: datetime64[ns]

In [82]:
from datetime import datetime

In [83]:
def check_weekday(date):
      
    # computing the parameter date
    # with len function
    res=len(pd.bdate_range(date,date))
      
    if res == 0 :
        return 'weekend'
    else:
        return 'weekday'

In [84]:
movie['weeknd'] = movie['release_date'].apply(check_weekday)

In [86]:
movie

,id,popularity,budget,revenue,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,weeknd
0,135397,32.985763,150000000.0,1.513529e+09,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,124.0,73,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,5562,6.5,2015,weekday
1,76341,28.419936,150000000.0,3.784364e+08,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,future|chase|post-apocalyptic|dystopia|australia,120.0,73,Village Roadshow Pictures|Kennedy Miller Produ...,2015-05-13,6185,7.1,2015,weekday
2,262500,13.112507,110000000.0,2.952382e+08,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,based on novel|revolution|dystopia|sequel|dyst...,119.0,338,Summit Entertainment|Mandeville Films|Red Wago...,2015-03-18,2480,6.3,2015,weekday
3,140607,11.173104,200000000.0,2.068178e+09,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,android|spaceship|jedi|space opera|3d,136.0,72,Lucasfilm|Truenorth Productions|Bad Robot,2015-12-15,5292,7.5,2015,weekday
4,168259,9.335014,190000000.0,1.506249e+09,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,car race|speed|revenge|suspense|car,137.0,130,Universal Pictures|Original Film|Media Rights ...,2015-04-01,2947,7.3,2015,weekday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10822,396,0.670274,7500000.0,3.373669e+07,Who's Afraid of Virginia Woolf?,Elizabeth Taylor|Richard Burton|George Segal|S...,Mike Nichols,alcohol|adultery|professor|married couple|son,131.0,530,Chenault Productions,1966-06-21,74,7.5,1966,weekday
10828,5780,0.402730,3000000.0,1.300000e+07,Torn Curtain,Paul Newman|Julie Andrews|Lila Kedrova|HansjÃ¶...,Alfred Hitchcock,cold war|east germany,128.0,849,Universal Pictures,1966-07-13,46,6.3,1966,weekday
10829,6644,0.395668,4653000.0,6.000000e+06,El Dorado,John Wayne|Robert Mitchum|James Caan|Charlene ...,Howard Hawks,sheriff|ranch|liquor|settler|revolver,120.0,213,Paramount Pictures|Laurel Productions,1966-12-17,36,6.9,1966,weekend
10835,5923,0.299911,12000000.0,2.000000e+07,The Sand Pebbles,Steve McQueen|Richard Attenborough|Richard Cre...,Robert Wise,missionary|china|us navy|chinese|battle,182.0,51,Twentieth Century Fox Film Corporation|Solar P...,1966-12-20,28,7.0,1966,weekday
10848,2161,0.207257,5115000.0,1.200000e+07,Fantastic Voyage,Stephen Boyd|Raquel Welch|Edmond O'Brien|Donal...,Richard Fleischer,submarine|coma|claustrophobia|wound|laser,100.0,335,Twentieth Century Fox Film Corporation,1966-08-24,42,6.7,1966,weekday

In [87]:
def friday(date):
    temp = pd.Timestamp(date)
    if temp.day_name()=='Friday':
        return 1
    else:
        return 0

In [88]:
movie['friday'] = movie['release_date'].apply(friday)

In [89]:
movie

,id,popularity,budget,revenue,original_title,cast,director,keywords,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,weeknd,friday
0,135397,32.985763,150000000.0,1.513529e+09,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,monster|dna|tyrannosaurus rex|velociraptor|island,124.0,73,Universal Studios|Amblin Entertainment|Legenda...,2015-06-09,5562,6.5,2015,weekday,0
1,76341,28.419936,150000000.0,3.784364e+08,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,future|chase|post-apocalyptic|dystopia|australia,120.0,73,Village Roadshow Pictures|Kennedy Miller Produ...,2015-05-13,6185,7.1,2015,weekday,0
2,262500,13.112507,110000000.0,2.952382e+08,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,based on novel|revolution|dystopia|sequel|dyst...,119.0,338,Summit Entertainment|Mandeville Films|Red Wago...,2015-03-18,2480,6.3,2015,weekday,0
3,140607,11.173104,200000000.0,2.068178e+09,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,android|spaceship|jedi|space opera|3d,136.0,72,Lucasfilm|Truenorth Productions|Bad Robot,2015-12-15,5292,7.5,2015,weekday,0
4,168259,9.335014,190000000.0,1.506249e+09,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,car race|speed|revenge|suspense|car,137.0,130,Universal Pictures|Original Film|Media Rights ...,2015-04-01,2947,7.3,2015,weekday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10822,396,0.670274,7500000.0,3.373669e+07,Who's Afraid of Virginia Woolf?,Elizabeth Taylor|Richard Burton|George Segal|S...,Mike Nichols,alcohol|adultery|professor|married couple|son,131.0,530,Chenault Productions,1966-06-21,74,7.5,1966,weekday,0
10828,5780,0.402730,3000000.0,1.300000e+07,Torn Curtain,Paul Newman|Julie Andrews|Lila Kedrova|HansjÃ¶...,Alfred Hitchcock,cold war|east germany,128.0,849,Universal Pictures,1966-07-13,46,6.3,1966,weekday,0
10829,6644,0.395668,4653000.0,6.000000e+06,El Dorado,John Wayne|Robert Mitchum|James Caan|Charlene ...,Howard Hawks,sheriff|ranch|liquor|settler|revolver,120.0,213,Paramount Pictures|Laurel Productions,1966-12-17,36,6.9,1966,weekend,0
10835,5923,0.299911,12000000.0,2.000000e+07,The Sand Pebbles,Steve McQueen|Richard Attenborough|Richard Cre...,Robert Wise,missionary|china|us navy|chinese|battle,182.0,51,Twentieth Century Fox Film Corporation|Solar P...,1966-12-20,28,7.0,1966,weekday,0
10848,2161,0.207257,5115000.0,1.200000e+07,Fantastic Voyage,Stephen Boyd|Raquel Welch|Edmond O'Brien|Donal...,Richard Fleischer,submarine|coma|claustrophobia|wound|laser,100.0,335,Twentieth Century Fox Film Corporation,1966-08-24,42,6.7,1966,weekday,0

In [226]:
movie[['friday','popularity']].corr()

              friday  popularity
friday      1.000000   -0.171462
popularity -0.171462    1.000000

In [91]:
movie['weeknd'] = enc.fit_transform(movie['weeknd'].values)

In [227]:
movie[['weeknd','popularity']].corr()

             weeknd  popularity
weeknd      1.00000    -0.01479
popularity -0.01479     1.00000

In [93]:
def weekday(date):
    temp = pd.Timestamp(date)
    return temp.day_name()

In [94]:
movie['weekday'] = movie['release_date'].apply(weekday)

In [95]:
movie['weekday'].value_counts()

Friday       1594
Thursday      752
Wednesday     627
Tuesday       258
Monday        171
Saturday      145
Sunday        131
Name: weekday, dtype: int64

In [71]:
df.dropna(inplace=True)

In [72]:
df.isnull().sum()

id                      0
popularity              0
budget                  0
revenue                 0
original_title          0
cast                    0
director                0
keywords                0
runtime                 0
genres                  0
production_companies    0
release_date            0
vote_count              0
vote_average            0
release_year            0
dtype: int64

In [98]:
movie['director'] = enc.fit_transform(movie['director'].values)

In [99]:
movie[['director','revenue']].corr()

          director   revenue
director  1.000000 -0.011834
revenue  -0.011834  1.000000

In [104]:
movie['weekday'] = enc.fit_transform(movie['weekday'].values)

In [105]:
from sklearn.linear_model import LinearRegression

In [352]:
lr = LinearRegression()

In [353]:
y=movie['popularity']

In [354]:
X = movie[['budget','vote_count','vote_average','weeknd','friday','revenue']]

In [355]:
from sklearn.model_selection import train_test_split

In [356]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [357]:
from sklearn.preprocessing import StandardScaler

In [381]:
min_max_scaler =MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_test_minmax = min_max_scaler.transform(X_test)

In [382]:
lr.fit(X_train_minmax,y_train)

LinearRegression()

In [383]:
predictions = lr.predict(X_test_minmax)

In [384]:
from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

MAE: 0.4349718470751823
MSE: 1.0761193040712493
RMSE: 1.0373617035881213

In [385]:
coeffecients = pd.DataFrame(lr.coef_,X.columns)
coeffecients.columns = ['Coeffecient']
coeffecients

              Coeffecient
budget           0.896509
vote_count      12.253553
vote_average     0.381627
weeknd          -0.010438
friday          -0.038421
revenue         -0.623573

# Ridge Regression

In [386]:
from sklearn.linear_model import Ridge

In [387]:
rg = Ridge(random_state=42)

In [388]:
rg.fit(X_train_minmax,y_train)

Ridge(random_state=42)

In [389]:
rg_pred = rg.predict(X_test_minmax)

In [390]:
from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, rg_pred))
print('MSE:', metrics.mean_squared_error(y_test, rg_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, rg_pred)))

MAE: 0.4358870266114403
MSE: 1.0673090205958042
RMSE: 1.0331064904431702

In [379]:
grid = dict()
grid['alpha'] = np.arange(0, 1, 0.01)
grid['tol']=[.001,.00001,.002,.0001,.0002]
grid['fit_intercept']=[True,False]
grid['solver']=['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']

In [442]:
from sklearn.model_selection import GridSearchCV, cross_validate
from sklearn.model_selection import RepeatedKFold

In [392]:
rg_tune=Ridge(random_state=42)

In [393]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=42)

In [426]:
rg_model = GridSearchCV(rg_tune,param_grid=grid ,cv=cv, scoring='neg_mean_squared_error',n_jobs=-1)

In [427]:
rg_result = rg_model.fit(X_train_minmax, y_train)

In [428]:
rg_result.best_score_

-0.8250244391857638

In [429]:
rg_result.best_params_

{'alpha': 0.25, 'fit_intercept': True, 'solver': 'saga', 'tol': 0.001}

In [458]:
#print(rg_model.cv_results_['mean_score_time'][rg_model.best_index_], rg_model.cv_results_['std_score_time'][rg_model.best_index_])

In [430]:
rg_ = Ridge(alpha=.25,fit_intercept=True,solver='saga',tol=.001,random_state=42)

In [445]:
results = cross_validate(rg_, X_train_minmax,  y_train,return_train_score = True, cv  = cv, scoring='neg_mean_squared_error')

In [459]:
print(results['test_score'].mean())

-0.8250244391857638